version: 2
updates:

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/variants/common/.github/workflows"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
      - "github-actions"
